### ISSUE TITLE
Usage with complete mtDNAs

### ISSUE THREAD

**Issue by NicRamb** [EvolEcolGroup/mtDNAcombine#10]
Hi!
This is an amazing and very useful tool! I was wondering if it can also be used for complete mtDNA sequences, especially for QC and filtering steps?

Thank you,
Nicola

**Comment by EleanorFMiller** [comment]
Hi Nicola,

I have not tried it with full mtDNA sequences myself, but I can't think of any reason why it wouldn't work. 
Hope it proves useful for you.

Best,
Eleanor
