### ISSUE TITLE
Activate CircleCI for the public repo

### ISSUE THREAD

**Issue by richelbilderbeek** [EvolEcolGroup/mtDNAcombine#2]
Hi @EvolEcolGroup,

I was happy to see there is CirclCI check on this repo! However, when I submitted [this Pull Request](https://github.com/EvolEcolGroup/mtDNAcombine/pull/1), I saw that CircleCI was not triggered.

I found out why, from the README.md, as it still refers to a private version of the repo (notice the `mtDNAcombine_private`):

```
[![CircleCI](https://img.shields.io/circleci/build/github/EvolEcolGroup/mtDNAcombine_private/master?label=build%20%28master%29&logo=circleci&style=plastic&token=dbf19e075582baa257024cdbe7a75edf96f93517)](https://circleci.com/gh/EvolEcolGroup/mtDNAcombine_private/tree/master)
```

I suggest to activate CircleCI for this public repo, else the badge would be untruthful.

Thanks for doing CI :+1:

**Comment by EleanorFMiller** [comment]
Thank you for spotting this! 
The README.md has been revised and the badge is now relevant to the `mtDNAcombine` repo.

**Comment by richelbilderbeek** [comment]
Thanks for fixing it :+1:
