### ISSUE TITLE
Biostrings update inconsistency in dependencies

### ISSUE THREAD

**Issue by EleanorFMiller** [EvolEcolGroup/mtDNAcombine#3]
An apparent inconsistency in dependency packages for the most recent version of `Biostrings` (`S4Vectors` in particular) is causing an issue within the continuous integration docker (running R v3.6.3). 
Working to resolve this.
CircleCI badge temporarily removed.

**Comment by dramanica** [comment]
This is now fixed in 34fb5d2235720e6cf5eba59025efd1a0dabd3085
